version: '3.9'

services:
  app:
    image: beenice_app
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: beenice_app
    ports:
      - '3000:3000'
    volumes:
      - ..:/app
    network_mode: bridge
